[package]
name = "physics"
version = "0.1.0"
edition = "2026"

[dependencies]
vectors = { path = "../vectors", version = "^0.1" }

[profile.debug]
optimization = 0

[profile.release]
optimization = 3
