[package]
name = "reimer-parser"
description = "Recursive-descent parser for Reimer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
reimer-ast = { path = "../reimer-ast" }
reimer-diagnostics = { path = "../reimer-diagnostics" }
reimer-lexer = { path = "../reimer-lexer" }

[lints]
workspace = true
