[workspace]
members = [
    "crates/reimer-ast",
    "crates/reimer-cli",
    "crates/reimer-codegen-native",
    "crates/reimer-diagnostics",
    "crates/reimer-hir",
    "crates/reimer-lexer",
    "crates/reimer-layout",
    "crates/reimer-lint",
    "crates/reimer-lsp",
    "crates/reimer-parser",
    "crates/reimer-package",
    "crates/reimer-project",
    "crates/reimer-resolver",
    "crates/reimer-runtime",
    "crates/reimer-types",
    "tools/imgui-api-gen",
    "tools/sdl-api-gen",
    "tools/wgpu-api-gen",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"

[workspace.lints.rust]
future-incompatible = "warn"
nonstandard-style = "deny"
unsafe-code = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = 10 }
pedantic = { level = "warn", priority = 5 }
