[package]
name = "reimer-layout"
description = "Shared native type layouts for the Reimer compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
reimer-hir = { path = "../reimer-hir" }
reimer-types = { path = "../reimer-types" }

[dev-dependencies]
reimer-diagnostics = { path = "../reimer-diagnostics" }

[lints]
workspace = true
