use std::path::Path;

use reimer_ast::{
    ConstantDeclaration, EnumDeclaration, ExternFunction, Function, GenericParameter,
    ImplDeclaration, Item, StructDeclaration, TraitDeclaration, TraitMethod, WherePredicate,
};
use reimer_diagnostics::Span;
use reimer_package::{Package, display_symbol_name};

pub(crate) fn render(package: &Package, source_root: &Path, title: &str) -> String {
    let mut output = format!(
        "# {title}\n\n\
         Public API documentation generated by `reimer doc` from `///` comments.\n\n"
    );
    let mut documented_items = 0_usize;

    for item in &package.program.items {
        match item {
            Item::Function(function)
                if function.is_public && belongs_to_root(package, function.span, source_root) =>
            {
                render_function(package, &mut output, function, None);
                documented_items += 1;
            }
            Item::ExternFunction(function)
                if function.is_public && belongs_to_root(package, function.span, source_root) =>
            {
                render_extern_function(package, &mut output, function);
                documented_items += 1;
            }
            Item::Struct(declaration)
                if declaration.is_public
                    && belongs_to_root(package, declaration.span, source_root) =>
            {
                render_struct(package, &mut output, declaration);
                documented_items += 1;
            }
            Item::Enum(declaration)
                if declaration.is_public
                    && belongs_to_root(package, declaration.span, source_root) =>
            {
                render_enum(package, &mut output, declaration);
                documented_items += 1;
            }
            Item::Trait(declaration)
                if declaration.is_public
                    && belongs_to_root(package, declaration.span, source_root) =>
            {
                render_trait(package, &mut output, declaration);
                documented_items += 1;
            }
            Item::Constant(declaration)
                if declaration.is_public
                    && belongs_to_root(package, declaration.span, source_root) =>
            {
                render_constant(package, &mut output, declaration);
                documented_items += 1;
            }
            Item::Impl(implementation)
                if belongs_to_root(package, implementation.span, source_root) =>
            {
                documented_items += render_implementation(package, &mut output, implementation);
            }
            Item::Import(_)
            | Item::Function(_)
            | Item::ExternFunction(_)
            | Item::Struct(_)
            | Item::Enum(_)
            | Item::Trait(_)
            | Item::Impl(_)
            | Item::Constant(_)
            | Item::Comptime(_) => {}
        }
    }

    if documented_items == 0 {
        output.push_str("This package does not expose any public items.\n");
    }
    output
}

fn belongs_to_root(package: &Package, span: Span, source_root: &Path) -> bool {
    package
        .source_path(span)
        .is_some_and(|path| path.starts_with(source_root))
}

fn render_function(
    package: &Package,
    output: &mut String,
    function: &Function,
    owner: Option<&str>,
) {
    let source_name = display_symbol_name(&function.name.name);
    let display_name = owner.map_or_else(
        || source_name.clone(),
        |owner| format!("{owner}::{}", final_segment(&source_name)),
    );
    let signature_name = owner.map_or(source_name.as_str(), |_| final_segment(&source_name));
    let mut signature = String::new();
    signature.push_str("pub ");
    if function.is_comptime {
        signature.push_str("comptime ");
    }
    signature.push_str("fn ");
    signature.push_str(signature_name);
    signature.push_str(&render_generics(package, &function.generic_parameters));
    signature.push('(');
    signature.push_str(
        &function
            .parameters
            .iter()
            .map(|parameter| source(package, parameter.span))
            .collect::<Vec<_>>()
            .join(", "),
    );
    signature.push(')');
    if let Some(return_type) = &function.return_type {
        signature.push_str(" -> ");
        signature.push_str(source(package, return_type.span));
    }
    signature.push_str(&render_where(package, &function.where_predicates));
    signature.push(';');

    render_section(package, output, &display_name, &signature, function.span);
}

fn render_extern_function(package: &Package, output: &mut String, function: &ExternFunction) {
    let display_name = display_symbol_name(&function.name.name);
    let mut signature = format!("pub extern \"{}\" fn {display_name}(", function.abi);
    signature.push_str(
        &function
            .parameters
            .iter()
            .map(|parameter| source(package, parameter.span))
            .collect::<Vec<_>>()
            .join(", "),
    );
    signature.push(')');
    if let Some(return_type) = &function.return_type {
        signature.push_str(" -> ");
        signature.push_str(source(package, return_type.span));
    }
    signature.push(';');
    render_section(package, output, &display_name, &signature, function.span);
}

fn render_struct(package: &Package, output: &mut String, declaration: &StructDeclaration) {
    let display_name = display_symbol_name(&declaration.name.name);
    let mut signature = format!(
        "pub struct {display_name}{}{} {{\n",
        render_generics(package, &declaration.generic_parameters),
        render_where(package, &declaration.where_predicates)
    );
    let mut hidden_fields = false;
    for field in &declaration.fields {
        if field.is_public {
            signature.push_str("    ");
            signature.push_str(source(package, field.span).trim_end_matches(','));
            signature.push_str(",\n");
        } else {
            hidden_fields = true;
        }
    }
    if hidden_fields {
        signature.push_str("    // Private fields omitted.\n");
    }
    signature.push('}');
    render_section(package, output, &display_name, &signature, declaration.span);
    for field in declaration.fields.iter().filter(|field| field.is_public) {
        render_documented_member(
            package,
            output,
            &display_name,
            &field.name.name,
            source(package, field.span),
            field.span,
        );
    }
}

fn render_enum(package: &Package, output: &mut String, declaration: &EnumDeclaration) {
    let display_name = display_symbol_name(&declaration.name.name);
    let mut signature = format!(
        "pub enum {display_name}{}{} {{\n",
        render_generics(package, &declaration.generic_parameters),
        render_where(package, &declaration.where_predicates)
    );
    for variant in &declaration.variants {
        signature.push_str("    ");
        signature.push_str(source(package, variant.span).trim_end_matches(','));
        signature.push_str(",\n");
    }
    signature.push('}');
    render_section(package, output, &display_name, &signature, declaration.span);
    for variant in &declaration.variants {
        render_documented_member(
            package,
            output,
            &display_name,
            &variant.name.name,
            source(package, variant.span),
            variant.span,
        );
    }
}

fn render_trait(package: &Package, output: &mut String, declaration: &TraitDeclaration) {
    let display_name = display_symbol_name(&declaration.name.name);
    let mut signature = format!(
        "pub trait {display_name}{}",
        render_generics(package, &declaration.generic_parameters)
    );
    if !declaration.supertraits.is_empty() {
        signature.push_str(": ");
        signature.push_str(
            &declaration
                .supertraits
                .iter()
                .map(|bound| display_symbol_name(&bound.display()))
                .collect::<Vec<_>>()
                .join(" + "),
        );
    }
    signature.push_str(&render_where(package, &declaration.where_predicates));
    signature.push_str(" {\n");
    for method in &declaration.methods {
        signature.push_str("    ");
        signature.push_str(source(package, method.span).trim());
        signature.push('\n');
    }
    signature.push('}');
    render_section(package, output, &display_name, &signature, declaration.span);
    for method in &declaration.methods {
        render_trait_method(package, output, &display_name, method);
    }
}

fn render_trait_method(package: &Package, output: &mut String, owner: &str, method: &TraitMethod) {
    render_nested_section(
        package,
        output,
        &format!("{owner}::{}", method.name.name),
        source(package, method.span),
        method.span,
        true,
    );
}

fn render_constant(package: &Package, output: &mut String, declaration: &ConstantDeclaration) {
    let display_name = display_symbol_name(&declaration.name.name);
    let signature = format!(
        "pub const {display_name}: {} = {};",
        source(package, declaration.ty.span),
        source(package, declaration.value.span())
    );
    render_section(package, output, &display_name, &signature, declaration.span);
}

fn render_implementation(
    package: &Package,
    output: &mut String,
    implementation: &ImplDeclaration,
) -> usize {
    let owner = source(package, implementation.target.span).to_owned();
    let mut count = 0_usize;
    for method in &implementation.methods {
        if method.is_public {
            render_function(package, output, method, Some(&owner));
            count += 1;
        }
    }
    count
}

fn render_section(
    package: &Package,
    output: &mut String,
    display_name: &str,
    signature: &str,
    span: Span,
) {
    output.push_str("## `");
    output.push_str(display_name);
    output.push_str("`\n\n```reimer\n");
    output.push_str(signature);
    output.push_str("\n```\n\n");
    if let Some(documentation) = package.documentation(span) {
        output.push_str(&documentation);
        output.push_str("\n\n");
    } else {
        output.push_str("_No documentation provided._\n\n");
    }
}

fn render_documented_member(
    package: &Package,
    output: &mut String,
    owner: &str,
    name: &str,
    signature: &str,
    span: Span,
) {
    if package.documentation(span).is_none() {
        return;
    }
    render_nested_section(
        package,
        output,
        &format!("{owner}::{name}"),
        signature,
        span,
        false,
    );
}

fn render_nested_section(
    package: &Package,
    output: &mut String,
    display_name: &str,
    signature: &str,
    span: Span,
    show_missing_documentation: bool,
) {
    output.push_str("### `");
    output.push_str(display_name);
    output.push_str("`\n\n```reimer\n");
    output.push_str(signature.trim());
    output.push_str("\n```\n\n");
    if let Some(documentation) = package.documentation(span) {
        output.push_str(&documentation);
        output.push_str("\n\n");
    } else if show_missing_documentation {
        output.push_str("_No documentation provided._\n\n");
    }
}

fn render_generics(package: &Package, parameters: &[GenericParameter]) -> String {
    if parameters.is_empty() {
        return String::new();
    }
    format!(
        "<{}>",
        parameters
            .iter()
            .map(|parameter| source(package, parameter.span()))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn render_where(package: &Package, predicates: &[WherePredicate]) -> String {
    if predicates.is_empty() {
        return String::new();
    }
    format!(
        " where {}",
        predicates
            .iter()
            .map(|predicate| source(package, predicate.span))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn source(package: &Package, span: Span) -> &str {
    package.source_text(span).unwrap_or("<source unavailable>")
}

fn final_segment(name: &str) -> &str {
    name.rsplit("::").next().unwrap_or(name)
}
